title: "Laís Carneiro"
show_downloads: false
google_analytics: false
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-target-blank
gems:
  - jekyll-target-blank  
target-blank:
  css_class: ext-link
  add_css_classes: css-class-one css-class-two
  rel: nofollow